### ISSUE TITLE
MVM Credits covers up Bison meter, potentially others

### ISSUE THREAD

**Issue by TheDerpySage** [Zeesastrous/ZeesHUD#20]
![image](https://user-images.githubusercontent.com/11201157/104626313-5ef41800-565b-11eb-946b-a8df70096008.png)
I believe I am on the latest version, I updated yesterday.

**Comment by Zeesastrous** [comment]
Bison is the only thing that gets hidden AFAIK. I wanted to make proper custom assets for the Credits, so this should be fixed by Alpha IV.

**Comment by TheDerpySage** [comment]
Cool. great work btw, I swear i started pubbing again just because of this.
