### ISSUE TITLE
Hidden text on Loading Screen

### ISSUE THREAD

**Issue by AhRoon** [Zeesastrous/ZeesHUD#23]
There is hidden text on Loading Screen(such as Top Duel Wins, Community Map Made By), and it shouldn't be here when Loading. I apologize for having no screenshot because it cannot be captured because of freezing on Loading Screen.

**Comment by Zeesastrous** [comment]
Loading screen is getting re-done altogether in next version, so this might be fixed while I scrap the 2nd loading screen.
