### ISSUE TITLE
cp_degrootkeep final capture point timers are broken

### ISSUE THREAD

**Issue by AhRoon** [Zeesastrous/ZeesHUD#25]
On DeGroot Keep, if the both control points are captured by BLU team, the final capture point timer does not display properly.
![20210201143031_1](https://user-images.githubusercontent.com/25527589/106430525-47b48780-64af-11eb-9aa0-80a4edccc664.jpg)
![20210201143547_1](https://user-images.githubusercontent.com/25527589/106430529-497e4b00-64af-11eb-912c-5a951d988fdf.jpg)

**Comment by raspimana** [comment]
I'll see if this is still true as of alpha IV.

**Comment by raspimana** [comment]
I think it's fine now but should move it up a notch.
![image](https://user-images.githubusercontent.com/36178983/110359449-5b916300-7ff2-11eb-8ca6-671657ea7122.png)
