### ISSUE TITLE
metal not centred on macos

### ISSUE THREAD

**Issue by sergentbne** [Zeesastrous/ZeesHUD#26]
idk if its a macos bug or a hud bug.

[](https://imgur.com/n1571AD)
[](https://imgur.com/MXArxqw``)

**Comment by sergentbne** [comment]
here is the link to the images
https://imgur.com/MXArxqw
https://imgur.com/n1571AD

**Comment by RegDuy** [comment]
The hud only is officaly supported on windows so you have to fix this yourself
