### ISSUE TITLE
Using latest commit, medic uber meter is positioned incorrectly

### ISSUE THREAD

**Issue by Rezulux** [Zeesastrous/ZeesHUD#28]
(As of commit 376923d)

Based on the positions of similarly styled meters (the Demoman's sticky charge meter and Sniper's bow charge meter) it seems as if the Medic's uber meter is positioned incorrectly, instead being placed at the upper left corner of the screen.

Editing lines 70 and 71 of _zeeshud_base/layout.res to say `"xpos" "c-111"` and `"ypos" "c110"` positions the meter to precisely match the location of the previously mentioned meters.

I like the new direction you've taken with some of the HUD elements! Much more of a consistent overall design, I'll miss the big AMMO text behind the ammo display, but overall this is a positive change, I especially like how you've stylized the GUI look of the Engineer's HUD bits.

**Comment by Zeesastrous** [comment]
aware of this, i changed the layout file to make the centered uber meter possible but forgot to test it. this will be fixed first when my hiatus is done with.
