### ISSUE TITLE
JRPG Addons broken

### ISSUE THREAD

**Issue by Thedudeman100** [Zeesastrous/ZeesHUD#48]
When any of the health_jrpg addons are applied, a team colored line from the original health hud remains below it and in the case of the health_jrpg_horizbar there is no color to the health bar.

![image](https://user-images.githubusercontent.com/55598011/119212286-5b4b2480-ba85-11eb-9c24-42ea4b4983f7.png)
![image](https://user-images.githubusercontent.com/55598011/119212305-7f0e6a80-ba85-11eb-9714-256ca87cea6f.png)
![image](https://user-images.githubusercontent.com/55598011/119212329-99e0df00-ba85-11eb-940e-b42793597329.png)

**Comment by Zeesastrous** [comment]
they're getting scrapped in the final version anyways
