### ISSUE TITLE
a simple question

### ISSUE THREAD

**Issue by cheekybaguette** [Zeesastrous/ZeesHUD#50]
Why do I get called an asshole after deleting the supporters.res file? What's wrong with that? I can't edit files that are on my pc, especially a hud?

**Comment by RealHours** [comment]
![Money-Is-Calling-black-afth-swatch](https://user-images.githubusercontent.com/44280562/120687349-2b295b80-c45f-11eb-927e-54395ba4366a.png)

**Comment by SinnerTF2** [comment]
> 
> 
> ![Money-Is-Calling-black-afth-swatch](https://user-images.githubusercontent.com/44280562/120687349-2b295b80-c45f-11eb-927e-54395ba4366a.png)

this again?
why do they keep calling me smh

**Comment by cheekybaguette** [comment]
money calling me on the daily bro. but have to decline this one cause i need a genuine answer

**Comment by RealHours** [comment]
the devs are anti semites, leave as soon as possible

**Comment by Blueberryy** [comment]
![3x (4)](https://user-images.githubusercontent.com/36592509/120706336-65801080-c4d2-11eb-8068-8d46e0d2e87c.png)

**Comment by cheekybaguette** [comment]
https://i.imgur.com/Y64k6Bh.jpeg

**Comment by Zeesastrous** [comment]
i would've answered honestly if it wasn't dogshit trolling

**Comment by RealHours** [comment]
No.

**Comment by cheekybaguette** [comment]
i wasn't trolling but guess the tranny brain can't really get serious questions. can't wait for u to have another mental breakdown
