### ISSUE TITLE
hit marker doesn't seem to go away or be changed

### ISSUE THREAD

**Issue by thepuffpuff** [Zeesastrous/ZeesHUD#56]
it is red and looks dumb i would like it to not be red and also dumb

**Comment by raspimana** [comment]
Do you have a screenshot?

**Comment by PersonMeetup** [comment]
Not OP, but I believe they're talking about this:
![20210709121450_1](https://user-images.githubusercontent.com/42787368/125120174-597a0680-e0af-11eb-8811-ab64f081376f.jpg)
If I'm right, then all the OP needs to do is go into `ZeesHUD\#customizations\hitmarker.res`, and set visible to 0.
